call_payload_required_data = {
    "status": "Planned",
    "dateStart": "2024-07-06 21:45:00",
    "duration": 300,
    "direction": "Outbound",
    "assignedUserId": "6676212784e8d2cf5",
    "assignedUserName": "Luis Hernández",
    "acceptanceStatus": "None",
    "dateEnd": "2024-07-06 22:00:00",
    "name": "Llamada con solo data requerida",
    "reminders": [],
    "description": "Descripción de llamada con solo data requerida",
    "teamsIds": [],
    "teamsNames": {},
    "usersIds": [],
    "usersNames": {},
    "usersColumns": {},
    "contactsIds": [],
    "contactsNames": {},
    "contactsColumns": {},
    "leadsIds": [],
    "leadsNames": {},
    "leadsColumns": {},
    "dateEndDate": "2024-07-06 21:50:00"
}