payload_task = {
    "id": "6689b2f6e52f50812",
    "name": "asd",
    "deleted": False,
    "status": "Not Started",
    "priority": "Normal",
    "dateStart": None,
    "dateEnd": None,
    "dateStartDate": None,
    "dateEndDate": None,
    "dateCompleted": None,
    "isOverdue": False,
    "reminders": [],
    "description": None,
    "createdAt": "2024-07-06 21:11:18",
    "modifiedAt": "2024-07-06 21:11:18",
    "parentId": None,
    "parentType": None,
    "parentName": None,
    "accountId": None,
    "accountName": None,
    "contactId": None,
    "contactName": None,
    "createdById": "66744ee8d0ffd7849",
    "createdByName": "Admin",
    "modifiedByName": None,
    "assignedUserId": "66744ee8d0ffd7849",
    "assignedUserName": "Admin",
    "teamsIds": [],
    "teamsNames": {},
    "attachmentsIds": [],
    "attachmentsNames": {},
    "isFollowed": True,
    "followersIds": [
        "66744ee8d0ffd7849"
    ],
    "followersNames": {
        "66744ee8d0ffd7849": "Admin"
    },
    "emailName": None,
    "attachmentsTypes": {}
}