name: EspoCRM Pipeline Execution test by team Qates

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
    types: [ opened, reopened, synchronize ]
  workflow_dispatch:  

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Verify JSON files
      run: |
        test -f resources/payloads/mail_draft/payload_email_draft_success.json
        test -f resources/payloads/mail_draft/payload_email_draft_invalid_email_format.json
        test -f resources/payloads/activities/payload_activities.json
        test -f resources/payloads/calls/payload_call.json
        test -f resources/payloads/calls/payload_call.py
        test -f resources/payloads/contact/payload_contact.py
        test -f resources/payloads/contact/payload_contact_full_values.py
        test -f resources/payloads/mail_important/payload_mail_important.json
        test -f resources/payloads/meeting/payload_meeting.json
        test -f resources/payloads/tasks/payload_schema_task.json
        test -f resources/payloads/tasks/payload_tasks.py
        test -f resources/schemas/activity.json
        test -f resources/schemas/contact_error_post.json
        test -f resources/schemas/contact_post.json
        test -f resources/schemas/correoImportant.json
        test -f resources/schemas/email.json
        test -f resources/schemas/get_completeFields_all_calls_schema.json
        test -f resources/schemas/payload_meeting_schema.json
        test -f resources/schemas/post_call_schema_response.json
        test -f resources/schemas/presentation.json
        test -f resources/schemas/task.json

    - name: Run tests
      env:
        PYTHONPATH: ${{ github.workspace }}
      run: |
        source venv/bin/activate
        pytest --alluredir=allure-results

    - name: Publish Allure Results
      uses: actions/upload-artifact@v3
      with:
        name: allure-results
        path: allure-results

    - name: Generate Allure Report
      uses: simple-elf/allure-report-action@master
      if: always()
      with:
        allure_results: allure-results
        allure_report: allure-report
        allure_history: allure-history

    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_PAT }}
        publish_branch: gh-pages
        publish_dir: allure-report

