name: EspoCRM Pipeline Execution test by team Qates

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
    types: [ opened, reopened, synchronize ]
  workflow_dispatch:  # Permitir ejecución manual

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Create dummy JSON files
      run: |
        mkdir -p core/payloads/mail_draft
        mkdir -p core/payloads/activities
        mkdir -p core/payloads/calls
        mkdir -p core/payloads/contact
        mkdir -p core/payloads/mail_important
        mkdir -p core/payloads/meeting
        mkdir -p core/payloads/tasks
        mkdir -p resources/schemas

        # Mail Draft Payloads
        echo '{}' > core/payloads/mail_draft/payload_email_draft_success.json
        echo '{}' > core/payloads/mail_draft/payload_email_draft_invalid_email_format.json

        # Activities Payloads
        echo '{}' > core/payloads/activities/payload_activities.json

        # Calls Payloads
        echo '{}' > core/payloads/calls/payload_call.json
        echo '{}' > core/payloads/calls/payload_call.py

        # Contact Payloads
        echo '{}' > core/payloads/contact/payload_contact.py
        echo '{}' > core/payloads/contact/payload_contact_full_values.py

        # Mail Important Payloads
        echo '{}' > core/payloads/mail_important/payload_mail_important.json

        # Meeting Payloads
        echo '{}' > core/payloads/meeting/payload_meeting.json

        # Tasks Payloads
        echo '{}' > core/payloads/tasks/payload_schema_task.json
        echo '{}' > core/payloads/tasks/payload_tasks.py

        # Schemas
        echo '{}' > resources/schemas/activity.json
        echo '{}' > resources/schemas/contact_error_post.json
        echo '{}' > resources/schemas/contact_post.json
        echo '{}' > resources/schemas/correoImportant.json
        echo '{}' > resources/schemas/email.json
        echo '{}' > resources/schemas/get_completeFields_all_calls_schema.json
        echo '{}' > resources/schemas/payload_meeting_schema.json
        echo '{}' > resources/schemas/post_call_schema_response.json
        echo '{}' > resources/schemas/presentation.json
        echo '{}' > resources/schemas/task.json

    - name: Run tests
      env:
        PYTHONPATH: ${{ github.workspace }}
      run: |
        source venv/bin/activate
        pytest --alluredir=allure-results

    - name: Publish Allure Results
      uses: actions/upload-artifact@v3
      with:
        name: allure-results
        path: allure-results

    - name: Generate Allure Report
      uses: simple-elf/allure-report-action@master
      if: always()
      with:
        allure_results: allure-results
        allure_report: allure-report
        allure_history: allure-history

    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_PAT }}
        publish_branch: gh-pages
        publish_dir: allure-report


