name: EspoCRM Pipeline Execution test by team Qates

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
    types: [ opened, reopened, synchronize ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Copy JSON files
      run: |
        mkdir -p resources/{payloads/{mail_draft,activities,calls,contact,mail_important,meeting,tasks},schemas}
        
        # Copy payloads
        cp path/to/local/*.json resources/payloads/mail_draft/
        cp path/to/local/*.json resources/payloads/activities/
        cp path/to/local/*.{json,py} resources/payloads/calls/
        cp path/to/local/*.py resources/payloads/contact/
        cp path/to/local/*.json resources/payloads/mail_important/
        cp path/to/local/*.json resources/payloads/meeting/
        cp path/to/local/*.{json,py} resources/payloads/tasks/
        
        # Copy schemas
        cp path/to/local/*.json resources/schemas/

    - name: Run tests
      env:
        PYTHONPATH: ${{ github.workspace }}
      run: |
        source venv/bin/activate
        pytest --alluredir=allure-results

    - name: Publish Allure Results
      uses: actions/upload-artifact@v3
      with:
        name: allure-results
        path: allure-results

    - name: Generate Allure Report
      uses: simple-elf/allure-report-action@master
      if: always()
      with:
        allure_results: allure-results
        allure_report: allure-report
        allure_history: allure-history

    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: allure-history
